# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'ketch-ios-uikit-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ketch-ios-uikit-sample
  pod 'KetchSDK', :git => 'https://github.com/ketch-com/ketch-ios.git'

end
