import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Ketch script tag */}
        <Script
          dangerouslySetInnerHTML={{
            __html: `Inline content of your Ketch script tag here`,
          }}
        ></Script>

        {/* Optional: TCF Stub - TODO:SA - Add here */}
        <Script
          strategy="beforeInteractive" // TODO:SA - Thinking we want to use beforeInteractive here? See https://nextjs.org/docs/pages/building-your-application/optimizing/scripts#strategy
          dangerouslySetInnerHTML={{
            __html: `Inline content of your Ketch script tag here`,
          }}
        ></Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
